# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: agbero

gitea_urls:
  api: https://git.imaxinacion.net/api/v1/
  download: https://git.imaxinacion.net/
  origin: https://git.imaxinacion.net/aibox/agbero

builds:
  - id: agbero
    main: ./cmd/agbero
    binary: agbero
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X git.imaxinacion.net/aibox/agbero/internal/woos.Version={{.Version}}
      - -X git.imaxinacion.net/aibox/agbero/internal/woos.Commit={{.Commit}}
      - -X git.imaxinacion.net/aibox/agbero/internal/woos.Date={{.Date}}

archives:
  - id: default
    # Use 'formats' (plural) - Default to tar.gz for Linux/Mac
    formats:
      - tar.gz

    # Use 'format_overrides' to switch Windows to zip
    format_overrides:
      - goos: windows
        # Use 'formats' (plural) here too
        formats:
          - zip

    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

    files:
      - README.md
      - LICENSE
      - cmd/agbero/data/agbero.hcl
      - cmd/agbero/data/hosts.d/website.hcl
      - cmd/agbero/data/hosts.d/example.hcl
#      - src: cmd/data/agbero.hcl
#        dst: agbero.hcl

snapshot:
  version_template: "{{ .Tag }}-next"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'