version: 2

project_name: agbero

builds:
  - id: agbero
    main: ./cmd/agbero
    binary: agbero
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/agberohq/agbero/internal/version.Version={{.Version}}
      - -X github.com/agberohq/agbero/internal/version.Commit={{.Commit}}
      - -X github.com/agberohq/agbero/internal/version.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz

    format_overrides:
      - goos: windows
        formats:
          - zip

    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

    files:
      - README.md
      - LICENSE
      - cmd/agbero/data/agbero.hcl
      - cmd/agbero/data/hosts.d/web.hcl
      - cmd/agbero/data/hosts.d/admin.hcl
      - cmd/agbero/data/hosts.d/example.hcl
#      - src: cmd/data/agbero.hcl
#        dst: agbero.hcl

snapshot:
  version_template: "{{ .Tag }}-next"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'