package tlss

import (
	"sync"

	"github.com/olekukonko/ll"
)

type ChallengeStore struct {
	mu      sync.RWMutex
	tokens  map[string]string
	cluster ClusterBroadcaster
	logger  *ll.Logger
}

// NewChallengeStore initializes an in-memory repository for ACME tokens.
// It bridges standard HTTP-01 challenges to the gossip mesh.
func NewChallengeStore(logger *ll.Logger) *ChallengeStore {
	return &ChallengeStore{
		tokens: make(map[string]string),
		logger: logger.Namespace("acme"),
	}
}

// SetCluster binds the distributed broadcaster to the local store.
func (s *ChallengeStore) SetCluster(c ClusterBroadcaster) {
	s.cluster = c
}

// Present surfaces an ACME challenge token locally and relays it to peers.
// Allows any node in the cluster to respond successfully to Let's Encrypt.
func (s *ChallengeStore) Present(domain, token, keyAuth string) error {
	s.mu.Lock()
	s.tokens[token] = keyAuth
	s.mu.Unlock()

	s.logger.Fields("domain", domain, "token", token).Info("presenting acme challenge")

	if s.cluster != nil {
		s.cluster.BroadcastChallenge(token, keyAuth, false)
	}
	return nil
}

// CleanUp deletes a fulfilled challenge and broadcasts the teardown.
func (s *ChallengeStore) CleanUp(domain, token, keyAuth string) error {
	s.mu.Lock()
	delete(s.tokens, token)
	s.mu.Unlock()

	if s.cluster != nil {
		s.cluster.BroadcastChallenge(token, keyAuth, true)
	}
	return nil
}

// GetKeyAuth serves HTTP-01 validation requests directly from memory.
func (s *ChallengeStore) GetKeyAuth(token string) (string, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	val, ok := s.tokens[token]
	return val, ok
}

// SyncFromCluster registers ACME tokens generated by other nodes.
func (s *ChallengeStore) SyncFromCluster(token, keyAuth string, deleted bool) {
	s.mu.Lock()
	defer s.mu.Unlock()

	if deleted {
		delete(s.tokens, token)
	} else {
		s.tokens[token] = keyAuth
	}
}
