package xudp

import (
	"encoding/hex"
	"fmt"
)

// STUN wire format (RFC 5389):
//
//  0                   1                   2                   3
//  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
// +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
// |0 0|     STUN Message Type     |         Message Length        |
// +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
// |                   Magic Cookie (0x2112A442)                   |
// +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
// |                                                               |
// |                     Transaction ID (96 bits)                  |
// |                                                               |
// +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
//
// Minimum STUN header is 20 bytes.
// The two most-significant bits of the first byte MUST be 0x00.
// The magic cookie is always 0x2112A442 at bytes 4-7.
// Transaction ID is bytes 8-19 (12 bytes, 96 bits).
//
// We use the transaction ID as the session key because:
//   - It is globally unique per ICE session (generated by the STUN client)
//   - It survives network path changes (client IP/port can change mid-session
//     during ICE candidate switching) while the transaction ID stays the same
//   - This gives more stable session pinning than src:port alone

const (
	stunMinLen    = 20
	stunMagicB0   = 0x21
	stunMagicB1   = 0x12
	stunMagicB2   = 0xA4
	stunMagicB3   = 0x42
	stunTxIDStart = 8
	stunTxIDEnd   = 20
)

// stunMatcher implements Matcher for STUN/WebRTC ICE traffic.
type stunMatcher struct{}

func init() {
	registerMatcher(&stunMatcher{})
}

func (s *stunMatcher) Name() string { return "stun" }

// Match returns the STUN transaction ID (24-char hex string) as the
// session key.  Returns ("", false) for non-STUN datagrams.
func (s *stunMatcher) Match(data []byte) (string, bool) {
	if len(data) < stunMinLen {
		return "", false
	}

	// Top two bits of first byte must be 0b00 for STUN
	if data[0]&0xC0 != 0x00 {
		return "", false
	}

	// Magic cookie check
	if data[4] != stunMagicB0 || data[5] != stunMagicB1 ||
		data[6] != stunMagicB2 || data[7] != stunMagicB3 {
		return "", false
	}

	// Transaction ID: bytes 8-19
	txID := hex.EncodeToString(data[stunTxIDStart:stunTxIDEnd])
	return txID, true
}

// IsSTUN returns true if data looks like a STUN datagram.
// Exported for use in tests and health executor.
func IsSTUN(data []byte) bool {
	_, ok := (&stunMatcher{}).Match(data)
	return ok
}

// STUNBindingRequest returns a minimal STUN Binding Request datagram
// (20 bytes) with the given transaction ID.  Used by the health executor.
func STUNBindingRequest(txID [12]byte) []byte {
	pkt := make([]byte, 20)
	// Message type: Binding Request (0x0001)
	pkt[0] = 0x00
	pkt[1] = 0x01
	// Message length: 0 (no attributes)
	pkt[2] = 0x00
	pkt[3] = 0x00
	// Magic cookie
	pkt[4] = stunMagicB0
	pkt[5] = stunMagicB1
	pkt[6] = stunMagicB2
	pkt[7] = stunMagicB3
	// Transaction ID
	copy(pkt[8:], txID[:])
	return pkt
}

// STUNMessageType returns a human-readable name for a STUN message type.
// Used in debug logging.
func STUNMessageType(data []byte) string {
	if len(data) < 2 {
		return "unknown"
	}
	t := uint16(data[0])<<8 | uint16(data[1])
	switch t {
	case 0x0001:
		return "BindingRequest"
	case 0x0101:
		return "BindingSuccessResponse"
	case 0x0111:
		return "BindingErrorResponse"
	case 0x0003:
		return "AllocateRequest"
	case 0x0103:
		return "AllocateSuccess"
	case 0x0113:
		return "AllocateError"
	case 0x0004:
		return "RefreshRequest"
	case 0x0009:
		return "SendIndication"
	case 0x0010:
		return "DataIndication"
	default:
		return fmt.Sprintf("0x%04x", t)
	}
}
