const TT={IDENTIFIER:"IDENTIFIER",STRING:"STRING",NUMBER:"NUMBER",BOOLEAN:"BOOLEAN",NULL:"NULL",EQUALS:"EQUALS",COLON:"COLON",LBRACE:"LBRACE",RBRACE:"RBRACE",LBRACKET:"LBRACKET",RBRACKET:"RBRACKET",LPAREN:"LPAREN",RPAREN:"RPAREN",COMMA:"COMMA",DOT:"DOT",PLUS:"PLUS",MINUS:"MINUS",STAR:"STAR",SLASH:"SLASH",PERCENT:"PERCENT",EQ:"EQ",NEQ:"NEQ",LT:"LT",GT:"GT",LTE:"LTE",GTE:"GTE",AND:"AND",OR:"OR",NOT:"NOT",QUESTION:"QUESTION",ELLIPSIS:"ELLIPSIS",ARROW:"ARROW",TEMPLATE_START:"TEMPLATE_START",COMMENT:"COMMENT",BLOCK_COMMENT:"BLOCK_COMMENT",NEWLINE:"NEWLINE",EOF:"EOF"};class _Token{constructor(e,t,n,s,o){this.type=e,this.value=t,this.line=n,this.column=s,this.raw=o??String(t??"")}}class _Lexer{constructor(e){this.src=e,this.pos=0,this.line=1,this.col=1}next(){if(this._skipWS(),this.pos>=this.src.length)return new _Token(TT.EOF,null,this.line,this.col,"");const e=this.src[this.pos],t=this.line,n=this.col;if(e==="#"||e==="/"&&this._peek()==="/")return this._comment(t,n);if(e==="/"&&this._peek()==="*")return this._blockComment(t,n);if(e==="<"&&this._peek()==="<")return this._heredoc(t,n);if(e==="$"&&this._peek()==="{")return this.pos+=2,this.col+=2,new _Token(TT.TEMPLATE_START,"${",t,n,"${");if(e==='"')return this._string(t,n);if(this._isDigit(e)||e==="-"&&this._isDigit(this._peek()))return this._number(t,n);if(this._isLetter(e)||e==="_")return this._ident(t,n);const s=e+(this._peek()||""),o={"==":TT.EQ,"!=":TT.NEQ,"<=":TT.LTE,">=":TT.GTE,"&&":TT.AND,"||":TT.OR,"=>":TT.ARROW};if(o[s])return this.pos+=2,this.col+=2,new _Token(o[s],s,t,n,s);if(e+(this._peek()||"")+(this._peek(2)||"")==="...")return this.pos+=3,this.col+=3,new _Token(TT.ELLIPSIS,"...",t,n,"...");this.pos++,this.col++;const i={"=":TT.EQUALS,":":TT.COLON,"{":TT.LBRACE,"}":TT.RBRACE,"[":TT.LBRACKET,"]":TT.RBRACKET,"(":TT.LPAREN,")":TT.RPAREN,",":TT.COMMA,".":TT.DOT,"+":TT.PLUS,"-":TT.MINUS,"*":TT.STAR,"/":TT.SLASH,"%":TT.PERCENT,"<":TT.LT,">":TT.GT,"!":TT.NOT,"?":TT.QUESTION};if(i[e])return new _Token(i[e],e,t,n,e);if(e===`
`)return this.line++,this.col=1,new _Token(TT.NEWLINE,`
`,t,n,`
`);throw new Error(`Unexpected '${e}' at line ${t}:${n}`)}_peek(e=1){return this.src[this.pos+e]??null}_skipWS(){for(;this.pos<this.src.length;){const e=this.src[this.pos];if(e===" "||e==="	"||e==="\r")this.pos++,this.col++;else break}}_comment(e,t){const s=this.pos,o=this.src[this.pos];for(o==="/"&&this._peek()==="/"?(this.pos+=2,this.col+=2):(this.pos++,this.col++);this.pos<this.src.length&&this.src[this.pos]!==`
`;)this.pos++,this.col++;const n=this.src.slice(s,this.pos);return new _Token(TT.COMMENT,n,e,t,n)}_blockComment(e,t){const s=this.pos;for(this.pos+=2,this.col+=2;this.pos<this.src.length-1;){if(this.src[this.pos]==="*"&&this.src[this.pos+1]==="/"){this.pos+=2,this.col+=2;break}this.src[this.pos]===`
`?(this.line++,this.col=1):this.col++,this.pos++}const n=this.src.slice(s,this.pos);return new _Token(TT.BLOCK_COMMENT,n,e,t,n)}_heredoc(e,t){const i=this.pos;this.pos+=2,this.col+=2;let s=!1;this.src[this.pos]==="-"&&(s=!0,this.pos++,this.col++);const a=this.pos;for(;this.pos<this.src.length&&this.src[this.pos]!==`
`;)this.pos++,this.col++;const r=this.src.slice(a,this.pos).trim();this.pos<this.src.length&&(this.pos++,this.line++,this.col=1);const n=[];for(;this.pos<this.src.length;){const t=this.pos;for(;this.pos<this.src.length&&this.src[this.pos]!==`
`;)this.pos++;const e=this.src.slice(t,this.pos).trimEnd();if(e.trim()===r){this.pos<this.src.length&&(this.pos++,this.line++,this.col=1);break}n.push(e),this.pos<this.src.length&&(this.pos++,this.line++,this.col=1)}let o=n.join(`
`);if(s){const e=Math.min(...n.filter(e=>e.trim()).map(e=>e.match(/^(\s*)/)[1].length));o=n.map(t=>t.slice(e)).join(`
`)}return new _Token(TT.STRING,o,e,t,this.src.slice(i,this.pos))}_string(e,t){const s=this.pos;this.pos++,this.col++;let n="";for(;this.pos<this.src.length;){const e=this.src[this.pos];if(e==='"'){this.pos++,this.col++;break}if(e==="\\"){this.pos++,this.col++;const e=this.src[this.pos],t={n:`
`,t:"	",r:"\r",'"':'"',"\\":"\\"};n+=t[e]??e}else n+=e;this.pos++,this.col++}return new _Token(TT.STRING,n,e,t,this.src.slice(s,this.pos))}_number(e,t){const s=this.pos;for(this.src[this.pos]==="-"&&(this.pos++,this.col++);this.pos<this.src.length&&this._isDigit(this.src[this.pos]);)this.pos++,this.col++;if(this.src[this.pos]==="."&&this._isDigit(this._peek()))for(this.pos++,this.col++;this.pos<this.src.length&&this._isDigit(this.src[this.pos]);)this.pos++,this.col++;if("eE".includes(this.src[this.pos]))for(this.pos++,this.col++,"+-".includes(this.src[this.pos])&&(this.pos++,this.col++);this.pos<this.src.length&&this._isDigit(this.src[this.pos]);)this.pos++,this.col++;const n=this.src.slice(s,this.pos);return new _Token(TT.NUMBER,parseFloat(n),e,t,n)}_ident(e,t){const s=this.pos;for(;this.pos<this.src.length&&(this._isLetter(this.src[this.pos])||this._isDigit(this.src[this.pos])||"_-".includes(this.src[this.pos]));)this.pos++,this.col++;const n=this.src.slice(s,this.pos);return n==="true"||n==="false"?new _Token(TT.BOOLEAN,n==="true",e,t,n):n==="null"?new _Token(TT.NULL,null,e,t,n):new _Token(TT.IDENTIFIER,n,e,t,n)}_isDigit(e){return e>="0"&&e<="9"}_isLetter(e){return e>="a"&&e<="z"||e>="A"&&e<="Z"}}function _tokenise(e){const s=new _Lexer(e),t=[];let n;for(;(n=s.next()).type!==TT.EOF;)t.push(n);return t}export function formatHCL(e){const i=_tokenise(e);let t="",o=0,n=!1,s=null;const a=()=>"  ".repeat(o);for(let c=0;c<i.length;c++){const e=i[c],r=i[c+1];if(e.type===TT.NEWLINE){s?.type!==TT.NEWLINE&&(t+=`
`),n=!0,s=e;continue}if(e.type===TT.COMMENT||e.type===TT.BLOCK_COMMENT){n&&(t+=a(),n=!1),t+=e.raw,s=e;continue}if(e.type===TT.RBRACE){o=Math.max(0,o-1),t=t.trimEnd(),t+=`
`+a()+"}",s=e;continue}switch(n&&(t+=a(),n=!1),e.type){case TT.EQUALS:t+=" = ";break;case TT.COLON:t+=": ";break;case TT.ARROW:t+=" => ";break;case TT.COMMA:t+=",",r&&r.type!==TT.NEWLINE&&r.type!==TT.RBRACKET&&(t+=" ");break;case TT.LBRACE:t+=" {",o++,(!r||r.type===TT.NEWLINE)&&(t+=`
`,n=!0);break;case TT.STRING:t+='"'+e.value.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\n/g,`\\n`).replace(/\t/g,"\\t")+'"';break;case TT.AND:case TT.OR:case TT.EQ:case TT.NEQ:case TT.LT:case TT.GT:case TT.LTE:case TT.GTE:case TT.PLUS:case TT.MINUS:case TT.STAR:case TT.SLASH:case TT.PERCENT:t+=` ${e.raw} `;break;default:t+=e.raw}s=e}return t.trim()}const _esc=e=>String(e).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"),_cls={[TT.IDENTIFIER]:"hcl-id",[TT.STRING]:"hcl-str",[TT.NUMBER]:"hcl-num",[TT.BOOLEAN]:"hcl-kw",[TT.NULL]:"hcl-kw",[TT.COMMENT]:"hcl-cmt",[TT.BLOCK_COMMENT]:"hcl-cmt",[TT.EQUALS]:"hcl-op",[TT.COLON]:"hcl-op",[TT.ARROW]:"hcl-op",[TT.LBRACE]:"hcl-punc",[TT.RBRACE]:"hcl-punc",[TT.LBRACKET]:"hcl-punc",[TT.RBRACKET]:"hcl-punc",[TT.COMMA]:"hcl-punc",[TT.TEMPLATE_START]:"hcl-tmpl"};export function highlightHCL(e){let t="";const n=_tokenise(e);for(const e of n){if(e.type===TT.NEWLINE){t+=`
`;continue}const s=_cls[e.type],o=e.type===TT.STRING?'"'+_esc(e.value.replace(/\\/g,"\\\\").replace(/"/g,'\\"'))+'"':_esc(e.raw);t+=s?`<span class="${s}">${o}</span>`:o}return t}export function parseHCL(e){try{_tokenise(e);let t=0;for(const n of _tokenise(e))if(n.type===TT.LBRACE&&t++,n.type===TT.RBRACE&&(t--,t<0))throw new Error("Unexpected }");if(t!==0)throw new Error("Unclosed {");return{success:!0}}catch(e){return{success:!1,error:e.message}}}export function validateHCL(e){const t=parseHCL(e);return t.success?null:t.error}export const HCL_CSS=`
.hcl-id   { color: #9cdcfe; }
.hcl-str  { color: #ce9178; }
.hcl-num  { color: #b5cea8; }
.hcl-kw   { color: #569cd6; }
.hcl-cmt  { color: #6a9955; font-style: italic; }
.hcl-op   { color: #d4d4d4; }
.hcl-punc { color: #d4d4d4; }
.hcl-tmpl { color: #c586c0; }
`