export const PerfChart={render(e,t,n,s={}){const l=document.getElementById(e);if(!l)return;const g=l.clientWidth||360,u=l.clientHeight||110,o={top:14,right:8,bottom:20,left:36},_=g-o.left-o.right,f=u-o.top-o.bottom;if(!t?.length){l.innerHTML=`<div style="height:100%;display:flex;align-items:center;justify-content:center;color:var(--text-mute);font-size:11px;">No data</div>`;return}const S=s.unit??"",k=s.color??"var(--accent)",F=s.isInt??!1,j=s.warnAt??null,m=Math.max(...t);let r=s.maxY!==0[0]?s.maxY:m===0?1:m*1.15;const c=s.minY!==0[0]?s.minY:0;r<=c&&(r=c+1);const a=t.length,i=e=>o.left+e/Math.max(a-1,1)*_,h=e=>o.top+f-(Math.min(e,r)-c)/(r-c)*f,A=t.map((e,t)=>`${i(t).toFixed(1)},${h(e).toFixed(1)}`).join(" "),O=i(0).toFixed(1),C=i(a-1).toFixed(1),v=(o.top+f).toFixed(1),x=`M${O},${v} `+t.map((e,t)=>`L${i(t).toFixed(1)},${h(e).toFixed(1)}`).join(" ")+` L${C},${v} Z`,d=j!==null&&m>=j?"var(--danger)":k,E=e=>F?Math.round(e)+"":e>=1e3?(e/1e3).toFixed(1)+"k":e<10?e.toFixed(1):e.toFixed(0),w=[c,(c+r)/2,r].map(e=>({y:h(e),l:E(e)+S})),p=e=>new Date(e*1e3).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),y=Math.floor((a-1)/2),M=[{x:i(0),l:p(n[0]),a:"start"},{x:i(y),l:p(n[y]),a:"middle"},{x:i(a-1),l:p(n[a-1]),a:"end"}],b="pg_"+e;l.innerHTML=`<svg width="${g}" height="${u}" viewBox="0 0 ${g} ${u}">
            <defs><linearGradient id="${b}" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%"   stop-color="${d}" stop-opacity="0.18"/>
                <stop offset="100%" stop-color="${d}" stop-opacity="0.01"/>
            </linearGradient></defs>
            ${w.map(e=>`<line x1="${o.left}" y1="${e.y.toFixed(1)}" x2="${o.left+_}" y2="${e.y.toFixed(1)}" stroke="var(--border)" stroke-width="1" stroke-dasharray="3 3"/>`).join("")}
            <path d="${x}" fill="url(#${b})"/>
            <polyline points="${A}" fill="none" stroke="${d}" stroke-width="1.5" stroke-linejoin="round" stroke-linecap="round"/>
            <circle cx="${i(a-1).toFixed(1)}" cy="${h(t[a-1]).toFixed(1)}" r="3" fill="${d}" stroke="var(--bg)" stroke-width="1.5"/>
            ${w.map(e=>`<text x="${o.left-4}" y="${(e.y+3.5).toFixed(1)}" font-size="9" font-family="monospace" fill="var(--text-mute)" text-anchor="end">${e.l}</text>`).join("")}
            ${M.map(e=>`<text x="${e.x.toFixed(1)}" y="${u-3}" font-size="9" font-family="monospace" fill="var(--text-mute)" text-anchor="${e.a}">${e.l}</text>`).join("")}
        </svg>`}};window.PerfChart=PerfChart